Improve p2p tendermint p2p (#163)
* Reduce noisy tendermint logs

* Suppress logs for all entering

Use peermanager scores for blocksync peers and don't error out on block mismatch (#162)

* Use peermanager scores for blocksync peers

* Add debug

* Randomize

* debug

* use state to filter

* debug

* debug

* debug

* debug

* add comments

* don't err

* revert timeout

* Add missing param

* Remove flaky test

* fix nil

* debug

* debug

* debug

* debug

---------

Co-authored-by: Yiming Zang <50607998+yzang2019@users.noreply.github.com>

Perf: Increase buffer size for pubsub server to boost performance (#167)

* Increase buffer size for pubsub server

* Add more timeout for test failure

* Add more timeout

* Fix test split scripts

* Fix test split

* Fix unit test

* Unit test

* Unit test

[P2P] Optimize block pool requester retry and peer pick up logic (#170)

* P2P Improvements: Fix block sync reactor and block pool retry logic

Fix block sync auto restart not working as expected (#175)

Fix edge case for blocksync (#178)

Replay events during restart to avoid tx missing (#211)

Add a new config to speed up block sync (#244)

* Never switch to consensus due to timeout

* Add blocksync peer config to speed up block sync rate

* Fix config parsing

* Add some logs

feat: Exclude unconditional peers when connection limit checking (#245)

Improve Peer Score Algorithm (#248)

* feat: improve peer scoring algo

* debug

* debug

* more debug

* debug TryDiaNext

* remove log

* fix score type

* rever block sync logic

* rever block sync logic

* rever block sync logic

* Add block request log

* Add apply block latency

* add processEpeerEvent log back

* update unit test

* update unit test

---------

Co-authored-by: yzang2019 <zymfrank@gmail.com>

Add logs for blocksync

Add log to debug replay

Fix

Fix setBlock true false

Add more log for dialing

Add more logs

Add logs for missing height

Fix

Fix log

Fix log

Fix log

Fix bpr pool goroutine

Fix bpr pool goroutine

Fix goroutine leak

Fix goroutine leak

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -38,7 +38,8 @@ jobs:
       - name: Run Go Tests
         run: |
           NUM_SPLIT=20
-          make test-group-${{matrix.part}} NUM_SPLIT=20
+          make split-test-packages
+          make test-group-${{matrix.part}}
 
       - name: Upload coverage artifact
         uses: actions/upload-artifact@v3
@@ -86,3 +87,32 @@ jobs:
           file: ./coverage.txt
           token: ${{ secrets.CODECOV_TOKEN }}
           fail_ci_if_error: true
+
+
+  unit-test-check:
+    name: Unit Test Check
+    runs-on: ubuntu-latest
+    needs: tests
+    if: always()
+    steps:
+      - name: Get workflow conclusion
+        id: workflow_conclusion
+        uses: nick-fields/retry@v2
+        with:
+          max_attempts: 2
+          retry_on: error
+          timeout_seconds: 60
+          command: |
+              jobs=$(curl https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs)
+              job_statuses=$(echo "$jobs" | jq -r '.jobs[] | .conclusion')
+
+              for status in $job_statuses
+              do
+                echo "Status: $status"
+                if [[ "$status" == "failure" ]]; then
+                  echo "Some or all tests have failed!"
+                  exit 1
+                fi
+              done
+
+              echo "All tests have passed!"
